### ISSUE TITLE
The Google Translate page open up without the text selected

### ISSUE THREAD

**Issue by gibalmeida** [Slamdunk/google-translation-firefox-addon#1]
Hi.

I've been using the Google Translation Firefox Addon for a while without any problem. But recently I noticed the addon open the Google Translator page without the text that I have selected to translate.

Actually my Firefox version is 60. But I noticed the problem has been started before this version. Sorry, but I don't known which version the problem has been started.

**Comment by Slamdunk** [comment]
Hi, sorry for the late response.

I cannot reproduce the issue in FF 61, can you provide a more extended example?

**Comment by wiper2908** [comment]
Js

**Comment by Grossdm** [comment]
@gibalmeida,

Is there any chance that you have the preference `dom.event.clipboardevents.enabled` set to `false`?

That restricts access to your clipboard, so it could be a problem.

Doug®

**Comment by Smile4ever** [comment]
I suggest you try Translate Now: https://addons.mozilla.org/addon/translate-now/ (also supports the more accurate DeepL translation service)

**Comment by NetNerd** [comment]
Apologies if I'm actually experiencing a slightly different issue due to the amount of time passed since this, but I also get blank translation pages.

The issue is the `tl` parameter sent in the URL. Translating text gives me a URL as such: `https://translate.google.com/#view=home&op=translate&sl=auto&tl=en-US&text=example`, but `en-US` seems to not be a valid value. Changing it to `en` in the address bar gets translation working.

I would suggest checking for the destination language in a list of supported languages, and remove the country code if required to correctly match a supported language.  
Alternatively, the only language which requires country code should be `zh-TW`, so it would be pretty easy for now to just make it a special case and globally strip country code for other languages.

**Comment by Slamdunk** [comment]
Nice catch: can you propose a Pull Request for this?

**Comment by NetNerd** [comment]
My javascript is pretty darn weak, so it might be better left to you if you ever get a chance haha

edit: I can probably get it working of course, but don't expect a proper idiomatic solution

**Comment by NetNerd** [comment]
Well, since you haven't implemented it yet (no worries, I understand fully), I guess I'll try to come up with something at least for a PR.

**Comment by NetNerd** [comment]
I have a snippet that should work to correct the language, but I haven't had a chance to get setup with firefox dev edition yet to properly test it in an extension yet.
(insert after line 3 of background.js)
```
// remove country code except for in zh-CN and zh-TW
// (all other languages don't accept country code, as of Aug. 2020)
var ccLangs = ["zh-CN", "zh-TW"];
if (toLang.includes("-") && !ccLangs.includes(toLang)) toLang = toLang.split("-")[0];
```

If you're free to test it and commit @Slamdunk, that would be nice. Otherwise I'll try to get a PR in tomorrow.

**Comment by Slamdunk** [comment]
I don't remember neither how to test the extension, I've developed this years ago, if you can test it I would be very thankful.
BTW you can open already open the PR as Draft, so the code would be already ready (and not sunk in this page) :+1:

**Comment by NetNerd** [comment]
Ah, okay then.

For reference, my current understanding is that either of these will allow for installing the extension via firefox's extension manager for testing:
* Upload the extension as an unlisted extension to AMO so it gets properly signed and can be installed on any firefox version (inconvenient but requires no second browser installation)
*  i. Install developer edition of firefox
   ii. Set `xpinstall.signatures.required` to false in browser config
   iii. Now signing isn't required for that installation

**Comment by Slamdunk** [comment]
Neither of both: see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

**Comment by NetNerd** [comment]
Ah, I didn't realise that temporary addons don't need to be signed. That's great.

**Comment by NetNerd** [comment]
The proposed PR seems to be working as intended in ff 79.0.
Not tested in older versions, but I don't see why it wouldn't work.

**Comment by Slamdunk** [comment]
New version updated with the fix, now let's wait for AMO approval:

![immagine](https://user-images.githubusercontent.com/152236/90760791-b4add980-e2e2-11ea-9a6d-762f27d2f3e5.png)

**Comment by Slamdunk** [comment]
New version approved and ready for download:

![immagine](https://user-images.githubusercontent.com/152236/90761138-4289c480-e2e3-11ea-8fb7-b146f3c5cdbc.png)
